require("plugins.rose-pine")
require("plugins.lsp")
require("plugins.oil")
require("plugins.conform")
require("plugins.nvim-lint")
require("plugins.tmux")
require("plugins.treesitter")
-- require("plugins.yanky")
require("plugins.fugitive")
-- require("plugins.remote")

require("plugins.mini.starter")
require("plugins.mini.basics")
require("plugins.mini.extra")
require("plugins.mini.completion")
require("plugins.mini.icons")
require("plugins.mini.pairs")
require("plugins.mini.pick")
require("plugins.mini.surround")
require("plugins.mini.statusline")
require("plugins.mini.notify")

-- custom

require("plugins.sync-to-coder")
